### ISSUE TITLE
Roadmap for v1.0.0

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [BerkhanBerkdemir/list-of-houses#1]
This will be the initial version of the List of Houses and will cover

* Use your own user and session controller
* It should be ready to use for universities and colleges
* Be confident with *test*.

# Todo

- [ ] User model with privileges. At least `admin`, `employe` and `guest`
- [ ] Landing page will be *sign in* page
- [ ] Basic administration page for administrators
